### ISSUE TITLE
SOFIA access through astroquery?

### ISSUE THREAD

**Issue by s-goldman** [SOFIAObservatory/Recipes#17]
Would this be easy/useful?

**Comment by msgordon** [comment]
This should already exist through the IRSA interface.

**Comment by s-goldman** [comment]
Hey Michael, yeah I figured it would. Within astroquery I couldn't find the SOFIA catalogs using the ISRA option. I was going to probe further if anyone thought that it was useful. 

Do you know if this a "IRSA Image Server program interface (IBE) Query" thing? Could the astroquery servers just not have the SOFIA option yet?

**Comment by s-goldman** [comment]
Also, thanks for chiming in!

**Comment by msgordon** [comment]
SOFIA data is available through IBE, with the same searchable parameters as IRSA (and DCS before it):
`from astroquery.ipac.irsa.ibe import Ibe`
`Ibe.list_tables('sofia','sofia.plane')`
`Ibe.query_region(coordinate=..., mission='sofia', dataset='sofia.plane',....)`


I don't think the SOFIA archive is appropriate for the astroquery catalog system as there is no standard photometry catalog for SOFIA data.  The images are all processed the same way through the data reduction pipeline, but photometry remains project-specific (and instrument-specific).  There are certainly many projects with standardized photometry catalogs over large area surveys, and users can still perform coordinate searches through the IBE interface to find SOFIA data.  These data would also turn up in Vizier searches on SOFIA papers.

**Comment by s-goldman** [comment]
Awesome. I'll add this to the SOFIA cookbooks/tutorials that I've been working on. 

Thanks Michael!
